/**
 * API Endpoint Functions - Generated from OpenAPI Spec
 *
 * AUTO-GENERATED by type-generator-agent from generated-docs/specs/api-spec.yaml
 * Do not edit manually - regenerate with /api-mock-refresh or re-run DESIGN.
 *
 * Each function wraps the project's API client with the correct path, method,
 * and TypeScript types from api-generated.ts.
 */

import { get, post, put, apiClient } from '@/lib/api/client';
import type {
  PaymentBatchRead,
  PaymentBatchReadList,
  PaymentRead,
  PaymentReadList,
  PaymentsDashboardRead,
  CreatePaymentBatchRequest,
  ParkPaymentsRequest,
  UnparkPaymentsRequest,
  GetPaymentsParams,
  GetPaymentBatchesParams,
} from '@/types/api-generated';
import type { DefaultResponse } from '@/types/api';

// ─── Payment Batch Endpoints ──────────────────────────────────────────────────

/**
 * GET /v1/payment-batches
 * Get a list of all payment batches
 */
export function getPaymentBatches(
  params?: GetPaymentBatchesParams,
): Promise<PaymentBatchReadList> {
  return get<PaymentBatchReadList>('/v1/payment-batches', params);
}

/**
 * GET /v1/payment-batches/{Id}
 * Get payment batch by key
 */
export function getPaymentBatch(id: number): Promise<PaymentBatchRead> {
  return get<PaymentBatchRead>(`/v1/payment-batches/${id}`);
}

/**
 * POST /v1/payment-batches
 * Create payment batch
 * @param data - Payment IDs to include in the batch
 * @param lastChangedUser - Name of user performing the action (required by API)
 */
export function createPaymentBatch(
  data: CreatePaymentBatchRequest,
  lastChangedUser: string,
): Promise<DefaultResponse> {
  return post<DefaultResponse>('/v1/payment-batches', data, lastChangedUser);
}

/**
 * POST /v1/payment-batches/{Id}/download-invoice-pdf
 * Download invoice PDF for a payment batch (returns binary Blob)
 */
export function downloadPaymentBatchInvoicePdf(id: number): Promise<Blob> {
  return apiClient<Blob>(`/v1/payment-batches/${id}/download-invoice-pdf`, {
    method: 'POST',
    isBinaryResponse: true,
  });
}

// ─── Payment Endpoints ────────────────────────────────────────────────────────

/**
 * GET /v1/payments
 * Get a list of all payments
 */
export function getPayments(
  params?: GetPaymentsParams,
): Promise<PaymentReadList> {
  return get<PaymentReadList>('/v1/payments', params);
}

/**
 * GET /v1/payments/{Id}
 * Get payment by key
 */
export function getPayment(id: number): Promise<PaymentRead> {
  return get<PaymentRead>(`/v1/payments/${id}`);
}

/**
 * GET /v1/payments/dashboard
 * Get payments dashboard data
 */
export function getPaymentsDashboard(): Promise<PaymentsDashboardRead> {
  return get<PaymentsDashboardRead>('/v1/payments/dashboard');
}

/**
 * PUT /v1/payments/park
 * Park a set of payments
 */
export function parkPayments(data: ParkPaymentsRequest): Promise<void> {
  return put<void>('/v1/payments/park', data);
}

/**
 * PUT /v1/payments/unpark
 * Unpark a set of payments
 */
export function unparkPayments(data: UnparkPaymentsRequest): Promise<void> {
  return put<void>('/v1/payments/unpark', data);
}

// ─── Demo Administration Endpoints ───────────────────────────────────────────

/**
 * POST /demo/reset-demo
 * Reset demo data
 */
export function resetDemo(): Promise<void> {
  return post<void>('/demo/reset-demo');
}
