/**
 * API Types - Generated from OpenAPI Spec
 *
 * AUTO-GENERATED by type-generator-agent from generated-docs/specs/api-spec.yaml
 * Do not edit manually - regenerate with /api-mock-refresh or re-run DESIGN.
 *
 * These types correspond to the `components/schemas` section of the OpenAPI spec.
 * The existing base types (APIError, APIRequestConfig, etc.) remain in api.ts.
 */

// ─── Component Schema Types ───────────────────────────────────────────────────

export interface PaymentBatchRead {
  Id?: number;
  CreatedDate?: string;
  Status?: string;
  Reference?: string;
  LastChangedUser?: string;
  AgencyName?: string;
  PaymentCount?: number;
  TotalCommissionAmount?: number;
  TotalVat?: number;
}

export interface PaymentBatchReadList {
  PaymentBatchList?: PaymentBatchRead[];
}

export interface PaymentRead {
  Id?: number;
  Reference?: string;
  AgencyName?: string;
  ClaimDate?: string;
  AgentName?: string;
  LastChangedUser?: string;
  LastChangedDate?: string;
  AgentSurname?: string;
  BondAmount?: number;
  CommissionType?: string;
  GrantDate?: string;
  RegistrationDate?: string;
  Bank?: string;
  CommissionAmount?: number;
  VAT?: number;
  Status?: string;
  BatchId?: number;
}

export interface PaymentReadList {
  PaymentList?: PaymentRead[];
}

export interface PaymentStatusReportItem {
  Status?: string;
  PaymentCount?: number;
  TotalPaymentAmount?: number;
  CommissionType?: string;
  AgencyName?: string;
}

export interface ParkedPaymentsAgingReportItem {
  Range?: string;
  AgencyName?: string;
  PaymentCount?: number;
}

export interface PaymentsByAgencyReportItem {
  AgencyName?: string;
  PaymentCount?: number;
  TotalCommissionCount?: number;
  Vat?: number;
}

export interface PaymentsDashboardRead {
  PaymentStatusReport?: PaymentStatusReportItem[];
  ParkedPaymentsAgingReport?: ParkedPaymentsAgingReportItem[];
  TotalPaymentCountInLast14Days?: number;
  PaymentsByAgency?: PaymentsByAgencyReportItem[];
}

// ─── Inline Request Body Types ────────────────────────────────────────────────

export interface CreatePaymentBatchRequest {
  PaymentIds?: number[];
}

export interface ParkPaymentsRequest {
  PaymentIds?: number[];
}

export interface UnparkPaymentsRequest {
  PaymentIds?: number[];
}

// ─── Query Parameter Types ────────────────────────────────────────────────────
// Declared as type aliases extending Record so they are assignable to the
// get() client's params argument (Record<string, string | number | boolean | undefined>).

export type GetPaymentsParams = Record<
  string,
  string | number | boolean | undefined
> & {
  ClaimDate?: string;
  AgencyName?: string;
  Status?: string;
};

export type GetPaymentBatchesParams = Record<
  string,
  string | number | boolean | undefined
> & {
  Reference?: string;
  AgencyName?: string;
};
